name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        resolver: [nightly, lts-23, lts-22, lts-21, lts-20, lts-19, lts-18, lts-16, lts-14, lts-12]
        include:
          - os: macos-latest
            resolver: nightly
          - os: windows-latest
            resolver: nightly

    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Cache dependencies
        if:   runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          # This path does not work under Windows:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.resolver }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.resolver }}-

      - name: Build and run tests
        shell: bash
        run: |
            set -ex
            stack upgrade || curl -sSL https://get.haskellstack.org/ | sh -s - -f
            stack test --fast --no-terminal --resolver=${{ matrix.resolver }}
